"""Domain knowledge — policies, rules, vocabulary, and patterns for specific domains.

Domain knowledge is what differentiates a generic chatbot from a domain expert.
It's injected into agent prompts and critic evaluations to ensure agents
behave correctly for their specific business context.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class DomainKnowledge:
    """
    Knowledge about a specific business domain.
    
    This is injected into agents and critics to ensure domain-appropriate behavior.
    Can be loaded from a file, generated by LLM, or built programmatically.
    """
    domain: str = ""
    
    # Business rules and policies
    policies: list[str] = field(default_factory=list)
    
    # Compliance rules (used by ComplianceCritic)
    compliance_rules: list[str] = field(default_factory=list)
    
    # Domain vocabulary (so agents use correct terminology)
    vocabulary: dict[str, str] = field(default_factory=dict)
    
    # Quality criteria (what "good" looks like in this domain)
    quality_criteria: list[str] = field(default_factory=list)
    
    # Common failure patterns (learned from past mistakes)
    failure_patterns: list[dict[str, str]] = field(default_factory=list)
    
    # Reference documents / FAQ content
    reference_docs: list[str] = field(default_factory=list)
    
    # Escalation triggers (when to involve humans)
    escalation_triggers: list[str] = field(default_factory=list)

    def to_prompt_injection(self) -> str:
        """Convert knowledge to text that can be injected into agent prompts."""
        sections = []

        if self.policies:
            sections.append("## Business Policies\n" + "\n".join(f"- {p}" for p in self.policies))

        if self.compliance_rules:
            sections.append("## Compliance Rules (MUST follow)\n" + "\n".join(f"- {r}" for r in self.compliance_rules))

        if self.vocabulary:
            vocab_lines = [f"- {term}: {definition}" for term, definition in self.vocabulary.items()]
            sections.append("## Domain Vocabulary\n" + "\n".join(vocab_lines))

        if self.quality_criteria:
            sections.append("## Quality Standards\n" + "\n".join(f"- {c}" for c in self.quality_criteria))

        if self.failure_patterns:
            patterns = [f"- AVOID: {p.get('pattern', '')} → INSTEAD: {p.get('solution', '')}" for p in self.failure_patterns]
            sections.append("## Known Failure Patterns (avoid these)\n" + "\n".join(patterns))

        if self.escalation_triggers:
            sections.append("## Escalation Triggers (involve human when)\n" + "\n".join(f"- {t}" for t in self.escalation_triggers))

        return "\n\n".join(sections) if sections else ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize for storage."""
        return {
            "domain": self.domain,
            "policies": self.policies,
            "compliance_rules": self.compliance_rules,
            "vocabulary": self.vocabulary,
            "quality_criteria": self.quality_criteria,
            "failure_patterns": self.failure_patterns,
            "escalation_triggers": self.escalation_triggers,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DomainKnowledge":
        """Deserialize from dict."""
        return cls(**{k: v for k, v in data.items() if hasattr(cls, k)})

    @classmethod
    def from_file(cls, path: str) -> "DomainKnowledge":
        """Load from a JSON file."""
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls.from_dict(data)

    def save(self, path: str) -> None:
        """Save to a JSON file."""
        Path(path).write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")

    def __repr__(self) -> str:
        return (f"DomainKnowledge(domain={self.domain!r}, "
                f"policies={len(self.policies)}, rules={len(self.compliance_rules)})")


# ═══════════════════════════════════════════════════════════
# Pre-built domain knowledge bases
# ═══════════════════════════════════════════════════════════

DOMAIN_KNOWLEDGE: dict[str, DomainKnowledge] = {
    "customer_support": DomainKnowledge(
        domain="customer_support",
        policies=[
            "First response within 5 minutes",
            "Resolution target: 24 hours",
            "Always acknowledge the customer's frustration before problem-solving",
            "Offer alternatives when the requested solution isn't possible",
            "Follow up after resolution to confirm satisfaction",
        ],
        compliance_rules=[
            "MUST: verify customer identity before making account changes",
            "MUST: log all interactions in the ticket system",
            "NEVER: share customer data with unauthorized parties",
            "NEVER: promise specific timelines without checking with relevant team",
            "NEVER: make up information — say 'I don't know' and escalate",
        ],
        vocabulary={
            "CSAT": "Customer Satisfaction Score (1-5 rating)",
            "NPS": "Net Promoter Score (-100 to +100)",
            "SLA": "Service Level Agreement — response/resolution time targets",
            "FCR": "First Contact Resolution — resolved in one interaction",
            "churn": "Customer cancellation / leaving the service",
        },
        quality_criteria=[
            "Response is empathetic and professional",
            "Issue is clearly understood and restated",
            "Solution is actionable and specific",
            "Follow-up steps are clearly communicated",
            "No information is fabricated or assumed",
        ],
        failure_patterns=[
            {"pattern": "Agent provides incorrect refund amount", "solution": "Always query the database for exact charges before quoting refund amounts"},
            {"pattern": "Agent shares internal system names with customer", "solution": "Use customer-facing terms only (e.g., 'our system' not 'the Postgres database')"},
            {"pattern": "Agent makes promises about feature timelines", "solution": "Say 'I'll check with our product team' instead of committing to dates"},
        ],
        escalation_triggers=[
            "Customer mentions legal action or regulatory complaint",
            "Issue involves data breach or security incident",
            "Customer requests refund over $500",
            "Issue unresolved after 3 interactions",
            "Customer explicitly asks for a manager/supervisor",
        ],
    ),

    "software_development": DomainKnowledge(
        domain="software_development",
        policies=[
            "All code must have tests before merging",
            "No secrets in source code — use environment variables",
            "Follow existing code style and patterns in the project",
            "Write clear commit messages explaining WHY, not just WHAT",
        ],
        compliance_rules=[
            "MUST: run tests before declaring code complete",
            "MUST: handle errors — never swallow exceptions silently",
            "NEVER: hardcode credentials, API keys, or passwords",
            "NEVER: use eval() or exec() with user input",
            "NEVER: delete production data without backup",
        ],
        vocabulary={
            "PR": "Pull Request — a code change submission for review",
            "CI/CD": "Continuous Integration / Continuous Deployment",
            "LGTM": "Looks Good To Me — approval for code merge",
            "WIP": "Work In Progress — not ready for review yet",
        },
        quality_criteria=[
            "Code compiles without errors",
            "All existing tests still pass",
            "New functionality has test coverage",
            "No security vulnerabilities introduced",
            "Code is readable and well-documented",
        ],
        failure_patterns=[
            {"pattern": "Agent writes code without checking existing patterns", "solution": "Always read existing files first to match style"},
            {"pattern": "Agent creates files but doesn't test them", "solution": "Always run tests after creating/modifying code"},
            {"pattern": "Agent uses deprecated APIs", "solution": "Check documentation for current API versions"},
        ],
        escalation_triggers=[
            "Build failures that persist after 3 retries",
            "Security vulnerability detected",
            "Database migration that could lose data",
            "Changes affecting more than 10 files",
        ],
    ),

    "ecommerce": DomainKnowledge(
        domain="ecommerce",
        policies=[
            "Return policy: 30 days for unused items, 14 days for electronics",
            "Free shipping on orders over $50",
            "Price match guarantee within 7 days of purchase",
            "Customer loyalty program: 1 point per $1 spent",
        ],
        compliance_rules=[
            "MUST: verify order number before making changes",
            "MUST: confirm shipping address before processing",
            "NEVER: process refunds over $500 without human approval",
            "NEVER: share payment details (show only last 4 digits)",
        ],
        quality_criteria=[
            "Order details are accurate",
            "Customer gets clear delivery timeline",
            "Return/refund process is clearly explained",
            "Upsell suggestions are relevant and not pushy",
        ],
        escalation_triggers=[
            "Fraud suspected on an order",
            "Refund amount exceeds $500",
            "Shipping damage claim",
            "Customer threatens chargeback",
        ],
    ),
}


def get_domain_knowledge(domain: str) -> DomainKnowledge:
    """Get pre-built knowledge for a domain, or return empty knowledge."""
    # Normalize domain name
    domain_key = domain.lower().replace(" ", "_").replace("-", "_")
    
    # Try exact match
    if domain_key in DOMAIN_KNOWLEDGE:
        return DOMAIN_KNOWLEDGE[domain_key]
    
    # Try partial match
    for key, knowledge in DOMAIN_KNOWLEDGE.items():
        if key in domain_key or domain_key in key:
            return knowledge
    
    # Return empty knowledge
    return DomainKnowledge(domain=domain)
